### ISSUE TITLE
curl Error

### ISSUE THREAD

**Issue by Fuin** [Kolyunya/codeception-markup-validator#83]
Hey, 

I am trying to get your Addon to work on my computer but I got a problem with the curl options. 
It startet out with curl error number 60 
so I downloaded this cacert.pm file and put it in my php.ini
and now I got the curl error number 77
and still cant figure out what the problem is.

I really absolutely dont know anything about curl and ssl so I dont have any plan what could be caousing this error. 
I want to check a https website, no htacces or anything else involved as far as I know.

**Comment by Fuin** [comment]
fixed it myself
because I am on windows cacert.pm is the wrong naming, I changed it to curl-ca-bundle.crt
and now its working..

**Comment by Kolyunya** [comment]
@Fuin just noticed the issue report. Glad you could fix it!
