### ISSUE TITLE
support for codeception 3.0.0

### ISSUE THREAD

**Issue by voku** [Kolyunya/codeception-markup-validator#84]
https://codeception.com/04-24-2019/codeception-3.0.html

EDIT: maybe you can move "codeception/codeception" into require-dev section from "composer.json"

**Comment by voku** [comment]
https://github.com/Kolyunya/codeception-markup-validator/pull/85

**Comment by Kolyunya** [comment]
@voku implemented in [3.1.0](https://github.com/Kolyunya/codeception-markup-validator/releases/tag/3.1.0). Thank you for your work. I've made some adjustments in your pull request to fix CI, tests, support older versions of PHP and PHPUnit.
