### ISSUE TITLE
Codeception v4 support

### ISSUE THREAD

**Issue by GJMichael** [Kolyunya/codeception-markup-validator#89]
Hi, I'm trying to install this on a project with codeception v4.1, and it fails with the following message:

kolyunya/codeception-markup-validator 3.1.0 requires codeception/codeception ^2.0 || ^3.0 -> satisfiable by codeception/codeception[2.0.0, 2.0.0-RC, 2.0.0-RC2, 2.0.0-alpha, 2.0.0-beta, 2.0.1, 2.0.10, 2.0.10.1, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.0.16, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.1.0-beta, 2.1.0-rc1, 2.1.1, 2.1.10, 2.1.11, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.2.0, 2.2.0-RC, 2.2.0-RC2, 2.2.0-beta, 2.2.1, 2.2.10, 2.2.11, 2.2.12, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.x-dev, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.x-dev, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.x-dev, 3.1.0, 3.1.1, 3.1.2, 3.1.x-dev] but these conflict with your requirements or minimum-stability.

Any reason 4.1 is not supported? Thanks!

**Comment by Kolyunya** [comment]
@GJMichael thank you for your feedback. We've added the Codeception v4 support in [`4.0.0`](https://github.com/Kolyunya/codeception-markup-validator/releases/tag/4.0.0). Reports of any possible problems while updating are greatly appreciated. Thank you!
